spring:
  application:
    name: onpremise-install-supporter

  cloud:
    openfeign:
      client:
        config:
          dockerHubFeignClient:
            loggerLevel: FULL

logging:
  level:
    jonghyeok.onpremiseinstallsupporter: DEBUG

image:
  path:
    file: ./images  # /app/data

github:
  url: https://api.github.com
