spring:
  application:
    name: onpremise-install-supporter

  cloud:
    openfeign:
      client:
        config:
          dockerHubFeignClient:
            loggerLevel: FULL

logging:
  level:
    jonghyeok.onpremiseinstallsupporter: DEBUG

docker-sync:
  enabled: true
  schedule:
    cron: 0 0 0 1 * ?
  file.path: ./images # /app/data
  github.url: https://api.github.com


